[project]
name = 'OrderFlow'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.orderflow-dex]
path = 'contracts\orderflow-dex.clar'
clarity_version = 3
epoch = '3.2'


[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
